### ISSUE TITLE
Audit script fails partway with OpenStack::Exception::ExpiredAuthToken

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/cwrc_preservation#30]
The audit script fails with an expired auth token partway through the audit process.

Possible fixes:
* increase efficiency of the audit script thus reducing run-time
* catch the expired auth token exception, authenticate, and restart audit a failure point

Note: this code is will become obsolete once CWRC v2.0 is in production (and CWRC v1.0 is decommissioned). ETA Dec. 2022. Thus, not spending significant time

**Comment by jefferya** [comment]
Efficiency: found way to approximately 50% reduction in Swift API calls. Due to the use of custom object metadata to store the CWRC object's last modification time (on the CWRC side), the Swift API doesn't appear to have bulk retrieval method (only the swift modification timestamp is available) so each object requires individual metadata retrieval .

Notes on exception handling:

The OpenStack Ruby client attempts to [retry (see here)](https://github.com/ruby-openstack/ruby-openstack/blob/373e0c47ab23b67c695873839282866d0849989a/lib/openstack/connection.rb#L243-L256). However, the retry fails with a HTTP 403 status, see below. 

```
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:648:in `initialize': Authentication failed with response code 403 (OpenStack::Exception::Authentication)
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:338:in `new'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:338:in `init'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:254:in `rescue in csreq'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:211:in `csreq'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:268:in `req'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/storage_object.rb:73:in `object_metadata'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/storage_object.rb:97:in `bytes'
        from ./cwrc_audit_report.rb:137:in `block in <module:CWRCPreserver>'
        from ./cwrc_audit_report.rb:128:in `each'
        from ./cwrc_audit_report.rb:128:in `<module:CWRCPreserver>'
        from ./cwrc_audit_report.rb:60:in `<main>'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:243:in `csreq': OpenStack::Exception::ExpiredAuthToken (OpenStack::Exception::ExpiredAuthToken)
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:268:in `req'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/storage_object.rb:73:in `object_metadata'
        from /usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/storage_object.rb:97:in `bytes'
        from ./cwrc_audit_report.rb:137:in `block in <module:CWRCPreserver>'
        from ./cwrc_audit_report.rb:128:in `each'
        from ./cwrc_audit_report.rb:128:in `<module:CWRCPreserver>'
        from ./cwrc_audit_report.rb:60:in `<main>'
```
